version: '3.8'

services:
  http-server-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "7777:7777"  # GDB debug port
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - CMAKE_BUILD_TYPE=Debug
      - HTTP_SERVER_HOST=0.0.0.0
      - HTTP_SERVER_PORT=8080
      - HTTP_SERVER_THREADS=4
      - ASAN_OPTIONS=detect_leaks=1:abort_on_error=1
      - UBSAN_OPTIONS=print_stacktrace=1:abort_on_error=1
    networks:
      - dev-net
    stdin_open: true
    tty: true
    security_opt:
      - seccomp:unconfined  # For debugging
    cap_add:
      - SYS_PTRACE  # For debugging

  # Code quality tools
  static-analysis:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
        echo 'Running static analysis...' &&
        cppcheck --enable=all --std=c++20 --suppress=missingIncludeSystem src/ include/ &&
        echo 'Running clang-format check...' &&
        find src include -name '*.cpp' -o -name '*.hpp' | xargs clang-format --dry-run --Werror
      "
    networks:
      - dev-net

  # Testing service
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app
    command: ./scripts/build.sh debug --tests
    networks:
      - dev-net

  # Benchmark service
  benchmark:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app
    command: ./scripts/benchmark.sh --tool ab --requests 1000 --concurrency 10
    depends_on:
      - http-server-dev
    networks:
      - dev-net

networks:
  dev-net:
    driver: bridge 